site_name: Neurenix Documentation
site_url: https://neurenix.github.io
site_description: Empowering Intelligent Futures, One Edge at a Time.
theme:
  name: github
  palette:
    primary: 'grey'
    accent: 'Cyan'

nav:
  - Home: index.md
  - Neurenix vs. Other AI Frameworks: FRAMEWORK_COMPARISON.md
  - Core | API: api/core.md
  - Distributed Computing | API: api/distributed_computing.md
  - Hugging Face Integration | API: api/huggingface_integration.md
  - Meta-Learning | API: api/meta_learning.md
  - Neural Networks | API: api/nn.md
  - Optimization | API: api/optimization.md
  - Reinforcement Learning | API: api/reinforcement_learning.md
  - Tensor Operations | API: api/tensor.md
  - Transfer Learning | API: api/transfer_learning.md
  - Unsupervised Learning | API: api/unsupervised_learning.md
  - WebAssembly Support | API: api/webassembly.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - footnotes
  - attr_list

plugins:
  - search

repo_url: https://github.com/MilesONerd/neurenix
