name: Notify Bot on Change

on:
  push:
    branches:
      - master  

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send repository_dispatch event to the bot repository
        run: |
          curl -X POST https://api.github.com/repos/Neurenix/Bot/dispatches \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.TOKEN_GITHUB }}" \
          -d '{"event_type": "update-neurenix"}'
